spring:
  application:
    name: store

stripe:
  apiUrl: https://api.stripe.com
  enable: true
  timeout: 1000
  support-currencies: TND, ALG, USD, EUR

payment-gateway: paypal

mail:
  host: https://stmp.gmail.com
  port: 5761